apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-site
  name: static-site
spec:
  replicas: 5
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - image: 212694347413.dkr.ecr.us-east-2.amazonaws.com/rolstadlearnk8s-frontend-static:16
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
