name: application-continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'src/app/**'
      - 'src/.docker/**'
  pull_request:
    branches: '**'
    paths:
      - 'src/app/**'
      - 'src/.docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
        shell: bash
    environment: production
    env:
      working-directory: ./src

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build Project
      run: echo 'Build'

    - name: Run Unit Tests
      run: echo 'Test'

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: rolstadlearnk8s-frontend-static
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -f .docker/nginx.dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG