name: k8s-service-deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
        shell: bash
    environment: production
    env:
      working-directory: ./src

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: us-east-2

    - name: Deploy Service
      uses: ianbelcher/eks-kubectl-action@master
      with:
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        args: apply -f .k8s/nginx.service.yml