name: terraform-continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
    paths: ./src/.infra/**
  pull_request:
    branches: '**' 
    paths: ./src/.infra/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/.infra
        shell: bash
    environment: production
    env:
      working-directory: ./src/.infra

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: ./src/.infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./src/.infra
